"use client";

import { useMemo, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Archive, ArrowDownToLine, CalendarDays, Check, ChevronDown, Download, Filter, MessageSquare, Paperclip, Pin, Plus, Printer, Search, SlidersHorizontal, X } from "lucide-react";
import { latestLogs, roomUpdates, serviceRequests, workOrders } from "@/lib/demo-data";
import { workspaceNames } from "@/lib/demo-data";
import type { WorkspaceRole } from "@/lib/permissions";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Card, CardHeader } from "./ui/card";
import { PageHeading } from "./dashboard/shared";

const moduleTitles: Record<string, [string, string]> = {
  incidents: ["Incidents", "Document, review, and resolve operational incidents."],
  "lost-found": ["Lost & Found", "Track found items from storage through final disposition."],
  "payment-issues": ["Payment discrepancies", "Resolve operational payment issues without duplicating billing."],
  "assigned-rooms": ["Assigned rooms", "Today’s room assignments and service priorities."],
  preventive: ["Preventive maintenance", "Scheduled inspections and recurring upkeep."],
  people: ["People & access", "Manage employees, roles, property access, and temporary passwords."],
  properties: ["Properties", "Manage organization properties and operational settings."],
  settings: ["Workspace settings", "Manage your preferences and department defaults."],
};

export function ModulePage({ role, module }: { role: WorkspaceRole; module: string }) {
  if (module === "operations-log") return <OperationsLog role={role}/>;
  if (module === "service-requests") return <ServiceRequests role={role}/>;
  if (module === "room-updates") return <RoomStatus/>;
  if (module === "work-orders") return <WorkOrders/>;
  if (module === "quality-scores") return <QualityScores/>;
  if (module === "reports") return <Reports/>;
  const [title, description] = moduleTitles[module] ?? [module.replaceAll("-", " "), "Operational records for this workspace."];
  return <GenericPage title={title} description={description} module={module}/>;
}

function Toolbar({ placeholder, action }: { placeholder: string; action?: React.ReactNode }) {
  return <div className="flex flex-col gap-3 sm:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">Search</span><Search className="absolute left-3.5 top-3.5 size-4 text-slate-400"/><input type="search" placeholder={placeholder} className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-4 text-sm shadow-sm placeholder:text-slate-400 focus:border-indigo-500"/></label><Button variant="secondary"><Filter className="size-4"/>Filters</Button>{action}</div>;
}

function OperationsLog({ role }: { role: WorkspaceRole }) {
  const [logs, setLogs] = useState(latestLogs);
  return <div className="space-y-6"><PageHeading eyebrow={workspaceNames[role]} title="Operations Log" description="A shared record of important updates across Ottawa Downtown." actions={<EntryDialog title="Add operations log" submitLabel="Publish update" fields={["Message", "Department visibility", "Priority", "Expiration date (optional)"]} onAdd={(message) => setLogs([{ id: `log-${Date.now()}`, author: "You", department: workspaceNames[role], time: "Just now", message, priority: "Standard", pinned: false }, ...logs])}/>}/>
    <Toolbar placeholder="Search messages, rooms, or authors…" action={<Button variant="secondary"><CalendarDays className="size-4"/>Date range</Button>}/>
    <div className="grid gap-6 xl:grid-cols-[1fr_270px]"><Card><div className="divide-y divide-slate-100">{logs.map((log) => <article key={log.id} className="px-5 py-5 sm:px-6"><div className="flex gap-3"><span className={`mt-1 size-2.5 shrink-0 rounded-full ${log.priority === "Urgent" ? "bg-rose-500" : log.priority === "Important" ? "bg-amber-500" : "bg-sky-500"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{log.author}</p><span className="text-xs text-slate-400">{log.department} · {log.time}</span>{log.pinned && <Badge tone="warning"><Pin className="mr-1 size-3"/>Pinned</Badge>}<Badge tone={log.priority === "Urgent" ? "urgent" : log.priority === "Important" ? "warning" : "info"}>{log.priority}</Badge></div><p className="mt-2 text-[15px] leading-6 text-slate-600">{log.message}</p><div className="mt-3 flex gap-4"><button className="inline-flex min-h-9 items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-indigo-600"><MessageSquare className="size-3.5"/>Reply</button><button className="inline-flex min-h-9 items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-indigo-600"><Paperclip className="size-3.5"/>Attachment</button></div></div></div></article>)}</div></Card>
      <aside className="space-y-4"><Card className="p-5"><p className="text-sm font-semibold text-slate-900">Viewing</p><div className="mt-4 space-y-3 text-sm text-slate-600"><FilterRow label="Department" value="All"/><FilterRow label="Priority" value="All"/><FilterRow label="Author" value="Anyone"/><FilterRow label="Pinned" value="Included"/></div></Card><p className="px-1 text-xs leading-5 text-slate-400">Entries are retained in the audit history. Archived entries remain available to authorized managers.</p></aside></div></div>;
}

function ServiceRequests({ role }: { role: WorkspaceRole }) {
  const [requests, setRequests] = useState(serviceRequests);
  const canCreate = role !== "maintenance" || true;
  return <div className="space-y-6"><PageHeading eyebrow={workspaceNames[role]} title="Service Requests" description="Coordinate operational requests from creation through completion." actions={canCreate ? <EntryDialog title="Create service request" submitLabel="Create request" fields={["Request title", "Description", "Room or location", "Assigned department", "Priority", "Due date"]} onAdd={(title) => setRequests([{ id: `SR-${1049 + requests.length}`, title, location: "Lobby", from: workspaceNames[role], assigned: "Maintenance", priority: "Standard", status: "Open", due: "Today" }, ...requests])}/> : undefined}/><Toolbar placeholder="Search requests, rooms, or locations…"/>
    <Card className="overflow-hidden"><div className="hidden grid-cols-[120px_1fr_150px_140px_130px_110px] gap-4 border-b border-slate-100 bg-slate-50/70 px-6 py-3 text-xs font-semibold uppercase tracking-wide text-slate-400 lg:grid"><span>Request</span><span>Details</span><span>Assigned to</span><span>Priority</span><span>Status</span><span>Due</span></div><div className="divide-y divide-slate-100">{requests.map((request) => <button key={request.id} className="grid w-full gap-3 px-5 py-4 text-left hover:bg-slate-50 sm:px-6 lg:grid-cols-[120px_1fr_150px_140px_130px_110px] lg:items-center lg:gap-4"><span className="text-sm font-semibold text-indigo-600">{request.id}</span><span className="min-w-0"><span className="block text-sm font-semibold text-slate-900">{request.title}</span><span className="mt-1 block text-xs text-slate-500">{request.location} · from {request.from}</span></span><span className="text-sm text-slate-600"><span className="mr-1 text-xs text-slate-400 lg:hidden">Assigned:</span>{request.assigned}</span><span><Badge tone={request.priority === "Urgent" ? "urgent" : request.priority === "High" ? "warning" : "neutral"}>{request.priority}</Badge></span><span><Badge tone={request.status === "Completed" ? "success" : request.status === "In Progress" ? "info" : "brand"}>{request.status}</Badge></span><span className={request.due === "Overdue" ? "text-sm font-semibold text-rose-600" : "text-sm text-slate-500"}>{request.due}</span></button>)}</div></Card></div>;
}

function RoomStatus() { return <div className="space-y-6"><PageHeading eyebrow="Housekeeping" title="Room status updates" description="Operational changes that affect room assignments and service type." actions={<EntryDialog title="Update room status" submitLabel="Share update" fields={["Room number", "Change type", "Operational details"]}/>}/><Toolbar placeholder="Search room number or update type…"/><Card><div className="divide-y divide-slate-100">{roomUpdates.map((u) => <article key={u.room} className="flex gap-4 px-5 py-5 sm:px-6"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-indigo-50 font-bold text-indigo-700">{u.room}</span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{u.type}</p><Badge tone={u.type === "Out of service" ? "urgent" : "info"}>{u.state}</Badge></div><p className="mt-1.5 text-sm text-slate-500">{u.detail}</p><p className="mt-2 text-xs text-slate-400">Updated by Alex Morgan · {u.time}</p></div></article>)}</div></Card></div>; }

function WorkOrders() { return <div className="space-y-6"><PageHeading eyebrow="Maintenance" title="Work Orders" description="Assigned repairs, preventive work, and completion history." actions={<EntryDialog title="Create work order" submitLabel="Create work order" fields={["Title", "Description", "Room or location", "Category", "Priority", "Assigned employee"]}/>}/><Toolbar placeholder="Search work orders…"/><Card><div className="divide-y divide-slate-100">{workOrders.map((o) => <article key={o.id} className="grid gap-3 px-5 py-5 sm:px-6 md:grid-cols-[120px_1fr_130px_140px] md:items-center"><p className="text-sm font-semibold text-indigo-600">{o.id}</p><div><p className="text-sm font-semibold text-slate-900">{o.title}</p><p className="mt-1 text-xs text-slate-500">{o.location} · {o.assignee}</p></div><Badge tone={o.priority === "Urgent" ? "urgent" : o.priority === "High" ? "warning" : "neutral"}>{o.priority}</Badge><Badge tone={o.status === "In Progress" ? "info" : "brand"}>{o.status}</Badge></article>)}</div></Card></div>; }

function QualityScores() { const scores = [{ d: "Front Desk", score: 94, target: 92, date: "Jul 15, 2026", type: "Brand review" }, { d: "Housekeeping", score: 91, target: 93, date: "Jul 10, 2026", type: "Quality inspection" }, { d: "Maintenance", score: 96, target: 90, date: "Jul 12, 2026", type: "Internal audit" }]; return <div className="space-y-6"><PageHeading eyebrow="Management" title="Department quality scores" description="Record review scores and follow progress without turning work into a game." actions={<EntryDialog title="Add quality score" submitLabel="Save score" fields={["Department", "Score", "Target score", "Review date", "Review type", "Comments (optional)"]}/>}/><div className="grid gap-4 md:grid-cols-3">{scores.map((s) => <Card key={s.d} className="p-5"><p className="text-sm font-semibold text-slate-900">{s.d}</p><div className="mt-5 flex items-end gap-2"><p className="text-4xl font-bold tracking-tight">{s.score}%</p><p className="mb-1 text-xs text-slate-400">Target {s.target}%</p></div><div className="mt-4 h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${s.score >= s.target ? "bg-emerald-500" : "bg-amber-500"}`} style={{ width: `${s.score}%` }}/></div><p className="mt-4 text-xs text-slate-500">{s.type} · {s.date}</p></Card>)}</div><Card><CardHeader title="Score history" description="Latest reviews across departments"/><div className="p-6 text-sm text-slate-500">Select a department above to view its complete score history and trend.</div></Card></div>; }

function Reports() { const [columns, setColumns] = useState(["Request ID", "Title", "Department", "Priority", "Status", "Created"]); return <div className="space-y-6"><PageHeading eyebrow="Management" title="Report builder" description="Choose a scope, preview the results, and export only the columns you need." actions={<Button variant="secondary"><Archive className="size-4"/>Saved templates</Button>}/><div className="grid gap-6 xl:grid-cols-[340px_1fr]"><Card className="h-fit p-5"><h2 className="font-semibold text-slate-900">Report criteria</h2><div className="mt-5 space-y-4"><FormSelect label="Report type" value="Service requests"/><FormSelect label="Date range" value="Last 30 days"/><FormSelect label="Property" value="Ottawa Downtown"/><FormSelect label="Department" value="All departments"/><FormSelect label="Status" value="All statuses"/><div><label className="text-sm font-semibold text-slate-700">Columns</label><div className="mt-2 flex flex-wrap gap-2">{columns.map((c) => <button key={c} onClick={() => setColumns(columns.filter((x) => x !== c))} className="inline-flex min-h-9 items-center gap-1 rounded-lg bg-indigo-50 px-2.5 text-xs font-semibold text-indigo-700">{c}<X className="size-3"/><span className="sr-only">Remove {c}</span></button>)}</div><Button variant="ghost" size="sm" className="mt-2"><Plus className="size-3.5"/>Add column</Button></div><Button className="w-full"><SlidersHorizontal className="size-4"/>Generate report</Button></div></Card><Card className="overflow-hidden"><CardHeader title="Preview" description={`${serviceRequests.length} rows · Updated just now`} action={<div className="flex gap-2"><Button size="sm" variant="secondary"><Download className="size-4"/>CSV</Button><Button size="sm" variant="secondary"><ArrowDownToLine className="size-4"/>Excel</Button><Button size="sm" variant="ghost"><Printer className="size-4"/><span className="sr-only">Print</span></Button></div>}/><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b bg-slate-50/70 text-xs uppercase tracking-wide text-slate-400">{columns.map((c) => <th key={c} className="px-5 py-3 font-semibold">{c}</th>)}</tr></thead><tbody>{serviceRequests.map((r) => <tr key={r.id} className="border-b last:border-0">{columns.map((c) => <td key={c} className="whitespace-nowrap px-5 py-4 text-slate-600">{c === "Request ID" ? r.id : c === "Title" ? r.title : c === "Department" ? r.assigned : c === "Priority" ? r.priority : c === "Status" ? r.status : "Aug 17, 2026"}</td>)}</tr>)}</tbody></table></div></Card></div></div>; }

function GenericPage({ title, description, module }: { title: string; description: string; module: string }) { const records = genericRecords(module); return <div className="space-y-6"><PageHeading eyebrow="Ottawa Downtown" title={title} description={description} actions={<EntryDialog title={`Add ${title.toLowerCase()}`} submitLabel="Save" fields={["Title or description", "Details", "Priority", "Assigned person"]}/>}/><Toolbar placeholder={`Search ${title.toLowerCase()}…`}/><Card>{records.length ? <div className="divide-y divide-slate-100">{records.map((r) => <article key={r.title} className="flex items-center gap-4 px-5 py-5 sm:px-6"><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{r.title}</p><p className="mt-1 text-sm text-slate-500">{r.detail}</p></div><Badge tone={r.tone}>{r.status}</Badge></article>)}</div> : <div className="grid min-h-72 place-items-center p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-slate-100 text-slate-500"><Archive className="size-5"/></span><h2 className="mt-4 font-semibold text-slate-900">Nothing here yet</h2><p className="mt-1 text-sm text-slate-500">New records will appear here when they’re added.</p></div></div>}</Card></div>; }

function EntryDialog({ title, submitLabel, fields, onAdd }: { title: string; submitLabel: string; fields: string[]; onAdd?: (value: string) => void }) { const [open, setOpen] = useState(false); const [saved, setSaved] = useState(false); function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); onAdd?.(String(form.get("field-0") || title)); setSaved(true); setTimeout(() => { setSaved(false); setOpen(false); }, 650); } return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><Button><Plus className="size-4"/>{title}</Button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-slate-950/35 backdrop-blur-sm"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><Dialog.Title className="text-xl font-bold tracking-tight text-slate-950">{title}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-slate-500">Complete the details below. Required fields are marked.</Dialog.Description></div><Dialog.Close className="grid size-10 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Close"><X className="size-5"/></Dialog.Close></div><form onSubmit={submit} className="mt-6 space-y-4">{fields.map((field, i) => <label key={field} className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-700">{field}{i < 2 && <span className="text-rose-600"> *</span>}</span>{field.toLowerCase().includes("description") || field === "Message" || field.includes("Details") ? <textarea name={`field-${i}`} required={i < 2} rows={3} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm focus:border-indigo-500" placeholder={`Enter ${field.toLowerCase()}`}/> : field.includes("date") ? <input name={`field-${i}`} type="date" required={i < 2} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm focus:border-indigo-500"/> : <input name={`field-${i}`} required={i < 2} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm focus:border-indigo-500" placeholder={`Enter ${field.toLowerCase()}`}/>}</label>)}<div className="flex justify-end gap-3 pt-2"><Dialog.Close asChild><Button type="button" variant="secondary">Cancel</Button></Dialog.Close><Button type="submit">{saved ? <><Check className="size-4"/>Saved</> : submitLabel}</Button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>; }

function FilterRow({ label, value }: { label: string; value: string }) { return <button className="flex min-h-10 w-full items-center justify-between rounded-lg px-2 hover:bg-slate-50"><span>{label}</span><span className="flex items-center gap-1 text-xs text-slate-400">{value}<ChevronDown className="size-3"/></span></button>; }
function FormSelect({ label, value }: { label: string; value: string }) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-700">{label}</span><button className="flex h-11 w-full items-center justify-between rounded-xl border border-slate-200 px-3 text-left text-sm text-slate-600"><span>{value}</span><ChevronDown className="size-4 text-slate-400"/></button></label>; }
function genericRecords(module: string): Array<{ title: string; detail: string; status: string; tone: "neutral" | "info" | "success" | "warning" | "urgent" }> { if (module === "incidents") return [{ title: "INC-209 · Guest relocation after AC issue", detail: "Room 604 · Assigned to Maya Chen", status: "Awaiting review", tone: "warning" }, { title: "INC-208 · Slip near pool entrance", detail: "Pool corridor · Follow-up completed", status: "Resolved", tone: "success" }]; if (module === "lost-found") return [{ title: "Black leather wallet", detail: "Found in Maple Room · Stored in safe B-12", status: "Guest contacted", tone: "info" }, { title: "Blue children’s backpack", detail: "Found in lobby · Pickup today at 4 PM", status: "Pickup arranged", tone: "success" }]; if (module === "payment-issues") return [{ title: "OTA virtual card difference · Room 521", detail: "$184.50 · Assigned to Maya Chen", status: "In review", tone: "warning" }, { title: "Tax exemption adjustment · Room 214", detail: "$42.17 · Supporting document received", status: "Assigned", tone: "info" }]; if (module === "properties") return [{ title: "Ottawa Downtown", detail: "142 rooms · America/Toronto", status: "Active", tone: "success" }, { title: "Ottawa Airport", detail: "118 rooms · America/Toronto", status: "Active", tone: "success" }]; if (module === "people") return [{ title: "Alex Morgan", detail: "Front Desk · Ottawa Downtown", status: "Active", tone: "success" }, { title: "Jordan Lee", detail: "Maintenance · Ottawa Downtown", status: "Active", tone: "success" }, { title: "Priya Shah", detail: "Housekeeping · Ottawa Downtown", status: "Temporary password", tone: "warning" }]; return []; }
