import { AlertTriangle, BookPlus, CheckCircle2, ClipboardPlus, FilePlus2, PackagePlus, Plus, RefreshCw, ShieldPlus, Sparkles, UserPlus, Wrench } from "lucide-react";
import { attention, roomUpdates, serviceRequests, workOrders } from "@/lib/demo-data";
import { Badge } from "../ui/badge";
import { Card, CardHeader } from "../ui/card";
import { ListRows, OperationsPreview, PageHeading, QualityScore, QuickActions } from "./shared";

export function FrontDeskDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Alex" description="Front Desk · Ottawa Downtown. Here’s what needs your attention today."/><QuickActions items={[{ label: "Create Service Request", icon: ClipboardPlus, primary: true }, { label: "Report Incident", icon: ShieldPlus }, { label: "Add Operations Log", icon: BookPlus }, { label: "Add Lost & Found Item", icon: PackagePlus }]}/>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader title="Needs attention" description="Operational items that may need your action"/><ListRows rows={attention.map((item) => ({ title: `${item.count} ${item.label}`, detail: item.detail, badge: item.tone === "urgent" ? "Overdue" : "Review", tone: item.tone as "urgent" | "warning" | "info" | "neutral" }))}/></Card><Card><CardHeader title="My open items" description="Requests and issues you created"/><ListRows rows={serviceRequests.slice(0, 3).map((r) => ({ title: `${r.id} · ${r.title}`, detail: `${r.location} · Assigned to ${r.assigned}`, badge: r.status, tone: r.status === "In Progress" ? "info" : "neutral" }))}/></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><OperationsPreview base="/app/front-desk"/><QualityScore department="Front Desk" score={94}/></div></div>;
}

export function HousekeepingDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Housekeeping" description="Good morning, Priya. Room changes and assignments for Ottawa Downtown."/><QuickActions items={[{ label: "Update Room Status", icon: RefreshCw, primary: true }, { label: "Report Room Issue", icon: AlertTriangle }, { label: "Request Support", icon: ClipboardPlus }, { label: "Add Operations Log", icon: BookPlus }]}/>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Room status updates" description="Reservation changes that affect today’s assignments"/><div className="divide-y divide-slate-100">{roomUpdates.map((update) => <button key={update.room} className="flex w-full gap-4 px-5 py-4 text-left hover:bg-slate-50 sm:px-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-indigo-50 font-bold text-indigo-700">{update.room}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{update.type}</p><Badge tone={update.type === "Out of service" ? "urgent" : update.type.includes("Stayover") ? "success" : "warning"}>{update.state}</Badge></div><p className="mt-1 text-sm leading-5 text-slate-500">{update.detail}</p></div><span className="hidden text-xs text-slate-400 sm:block">{update.time}</span></button>)}</div></Card><div className="space-y-6"><Card><CardHeader title="Today’s rooms"/><div className="grid grid-cols-2 gap-px overflow-hidden rounded-b-2xl bg-slate-100"><Metric label="Assigned" value="38"/><Metric label="Priority" value="7"/><Metric label="Ready" value="14"/><Metric label="Waiting" value="3"/></div></Card><QualityScore department="Housekeeping" score={91} change="+1%"/></div></div><OperationsPreview base="/app/housekeeping"/></div>;
}

export function MaintenanceDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Maintenance" description="Good morning, Jordan. Prioritized work for Ottawa Downtown."/><QuickActions items={[{ label: "Create Work Order", icon: Wrench, primary: true }, { label: "Report Completion", icon: CheckCircle2 }, { label: "Request Support", icon: ClipboardPlus }, { label: "Add Operations Log", icon: BookPlus }]}/>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader title="Priority work" description="Urgent and high-priority work orders first"/><div className="divide-y divide-slate-100">{workOrders.map((order) => <button key={order.id} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-slate-50 sm:px-6"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${order.priority === "Urgent" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}><Wrench className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{order.id} · {order.title}</p><p className="mt-1 text-sm text-slate-500">{order.location} · {order.assignee}</p></div><Badge tone={order.priority === "Urgent" ? "urgent" : order.priority === "High" ? "warning" : "neutral"}>{order.status}</Badge><span className="hidden text-xs text-slate-400 sm:block">{order.age}</span></button>)}</div></Card><div className="space-y-6"><Card><CardHeader title="Workload"/><ListRows rows={[{ title: "Preventive maintenance due", detail: "5 inspections due this week", badge: "5", tone: "warning" }, { title: "Recurring room issues", detail: "3 rooms with repeat reports", badge: "Review", tone: "urgent" }, { title: "Waiting for parts", detail: "2 work orders paused", badge: "2", tone: "neutral" }]}/></Card><QualityScore department="Maintenance" score={96}/></div></div><OperationsPreview base="/app/maintenance"/></div>;
}

export function ManagerDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Maya" description="Operations overview for Ottawa Downtown."/><QuickActions items={[{ label: "Create Announcement", icon: BookPlus, primary: true }, { label: "Assign Task", icon: ClipboardPlus }, { label: "View Reports", icon: FilePlus2 }, { label: "Manage Users", icon: UserPlus }]}/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Summary label="Open issues" value="24" note="Across 4 departments"/><Summary label="Overdue" value="5" note="2 urgent" urgent/><Summary label="Awaiting review" value="3" note="Incidents & payments"/><Summary label="Completed today" value="31" note="Up 12% from Monday" success/></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><OperationsPreview base="/app/manager"/><Card><CardHeader title="Department quality" description="Latest inspection scores"/><ListRows rows={[{ title: "Maintenance", detail: "Reviewed July 12", badge: "96%", tone: "success" }, { title: "Front Desk", detail: "Reviewed July 15", badge: "94%", tone: "success" }, { title: "Housekeeping", detail: "Reviewed July 10", badge: "91%", tone: "success" }, { title: "Food & Beverage", detail: "Reviewed June 28", badge: "88%", tone: "warning" }]}/></Card></div>
    <Card><CardHeader title="Recent escalations" description="Items that need management visibility"/><ListRows rows={[{ title: "Room 604 · Repeated AC issue", detail: "Third report in 30 days · Maintenance", badge: "Investigate", tone: "urgent" }, { title: "Virtual card discrepancy", detail: "OTA booking · Room 521 · $184.50", badge: "Assigned", tone: "warning" }, { title: "Guest relocation follow-up", detail: "Incident INC-209 · Front Desk", badge: "Review", tone: "info" }]}/></Card></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><p className="text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>; }
function Summary({ label, value, note, urgent, success }: { label: string; value: string; note: string; urgent?: boolean; success?: boolean }) { return <Card className="p-4 sm:p-5"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${urgent ? "bg-rose-500" : success ? "bg-emerald-500" : "bg-indigo-500"}`} aria-hidden="true"/><p className="text-xs font-semibold text-slate-500">{label}</p></div><p className="mt-3 text-3xl font-bold tracking-[-.04em] text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></Card>; }
