"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, BellRing, BookPlus, CheckCircle2, ClipboardPlus, Clock3, FilePlus2, PackagePlus, Plus, RefreshCw, ShieldPlus, Sparkles, UserPlus, Wrench } from "lucide-react";
import { workOrders } from "@/lib/demo-data";
import { updateRoomUpdateState, useRoomUpdates } from "@/lib/room-update-store";
import { useServiceRequests } from "@/lib/service-request-store";
import { useDepartmentNotifications } from "@/lib/notification-store";
import { demoEmployees, getDemoEmployeeSession, type DemoEmployee } from "@/lib/demo-auth";
import { Badge } from "../ui/badge";
import { Card, CardHeader } from "../ui/card";
import { ListRows, OperationsPreview, PageHeading, QuickActions } from "./shared";

export function FrontDeskDashboard() {
  const requests = useServiceRequests();
  const openStatuses = new Set(["Open", "Assigned", "In Progress", "Waiting"]);
  const needsAttention = requests.filter((request) => request.assigned === "Front Desk" && openStatuses.has(request.status));
  const myOpenItems = requests.filter((request) => (request.createdBy === "Alex Morgan" || request.from === "Front Desk") && openStatuses.has(request.status));
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Alex" description="Front Desk · Ottawa Downtown. Here’s what needs your attention today." actions={<CompactQualityScore department="Front Desk" score={94}/>}/><QuickActions items={[{ label: "Create Service Request", icon: ClipboardPlus, primary: true, href: "/app/front-desk/service-requests?create=1" }, { label: "Add Late Checkout", icon: Clock3, href: "/app/front-desk/room-updates?create=1" }, { label: "Report Incident", icon: ShieldPlus, href: "/app/front-desk/incidents?create=1" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/front-desk/operations-log?create=1" }, { label: "Add Lost & Found Item", icon: PackagePlus, href: "/app/front-desk/lost-found?create=1" }]}/>
    <RoomChangeSummary workspace="front-desk"/>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader title="Needs attention" description="Live work currently assigned to Front Desk"/>{needsAttention.length ? <ListRows rows={needsAttention.map((request) => ({ title: `${request.id} · ${request.title}`, detail: `${request.location} · Requested by ${request.from}`, badge: request.status, tone: request.priority === "Urgent" ? "urgent" : request.status === "In Progress" ? "info" : "warning", href: `/app/front-desk/service-requests?request=${request.id}` }))}/> : <DashboardEmpty message="No Front Desk actions need attention."/>}</Card><Card><CardHeader title="My open items" description="Live status of requests you created"/>{myOpenItems.length ? <ListRows rows={myOpenItems.map((request) => ({ title: `${request.id} · ${request.title}`, detail: `${request.location} · Assigned to ${request.assigned}`, badge: request.status, tone: request.status === "In Progress" ? "info" : request.status === "Waiting" ? "warning" : "neutral", href: `/app/front-desk/service-requests?request=${request.id}` }))}/> : <DashboardEmpty message="You have no open items."/>}</Card></div>
    <OperationsPreview base="/app/front-desk" role="front-desk"/></div>;
}

export function HousekeepingDashboard() {
  const updates = useRoomUpdates();
  const [employee, setEmployee] = useState<DemoEmployee | null>(null);
  useEffect(() => setEmployee(getDemoEmployeeSession("housekeeping") ?? demoEmployees["priya.shah"]), []);
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Housekeeping" description={`Good morning, ${employee?.name ?? "Housekeeping team"}. Room changes and assignments for Ottawa Downtown.`} actions={<CompactQualityScore department="Housekeeping" score={91}/>}/><QuickActions items={[{ label: "Update Room Status", icon: RefreshCw, primary: true, href: "/app/housekeeping/room-updates" }, { label: "Report Room Issue", icon: AlertTriangle, href: "/app/housekeeping/service-requests?create=1" }, { label: "Request Support", icon: ClipboardPlus, href: "/app/housekeeping/service-requests?create=1" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/housekeeping/operations-log?create=1" }]}/>
    {employee?.isSupervisor && <DepartmentReminders department="Housekeeping" base="/app/housekeeping"/>}
    <RoomChangeSummary workspace="housekeeping"/>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Room status updates" description="Reservation changes that affect today’s assignments"/><div className="divide-y divide-slate-100">{updates.filter((update) => update.type !== "Late checkout").map((update, index) => { const key = update.id ?? `${update.room}-${update.type}`; return <article key={`${key}-${index}`} className="flex flex-col gap-4 px-5 py-4 sm:flex-row sm:items-center sm:px-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-brand-soft font-bold text-brand-strong">{update.room}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{update.type}</p><p className="mt-1 text-sm leading-5 text-slate-500">{update.detail}</p><p className="mt-1 text-xs text-slate-400">{update.time}</p></div><label className="min-w-40"><span className="sr-only">Status for room {update.room}</span><select aria-label={`Status for room ${update.room}`} value={update.state} onChange={(event) => updateRoomUpdateState(update.id, `${update.room}-${update.type}`, event.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700 focus:border-brand"><option>Action needed</option><option>Assignment changed</option><option>Ready to assign</option><option>Waiting for clearance</option><option>Acknowledged</option><option>In Progress</option><option>Completed</option></select></label></article>; })}</div></Card><Card className="h-fit"><CardHeader title="Today’s rooms" action={<Link href="/app/housekeeping/assigned-rooms" className="text-xs font-semibold text-brand">Manage assignments</Link>}/><div className="grid grid-cols-2 gap-px overflow-hidden rounded-b-2xl bg-slate-100"><Metric label="Assigned" value="38"/><Metric label="Priority" value="7"/><Metric label="Ready" value="14"/><Metric label="Waiting" value="3"/></div></Card></div><OperationsPreview base="/app/housekeeping" role="housekeeping"/></div>;
}

export function MaintenanceDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Maintenance" description="Good morning, Jordan. Prioritized work for Ottawa Downtown." actions={<CompactQualityScore department="Maintenance" score={96}/>}/><QuickActions items={[{ label: "Create Work Order", icon: Wrench, primary: true, href: "/app/maintenance/work-orders?create=1" }, { label: "Report Completion", icon: CheckCircle2, href: "/app/maintenance/work-orders" }, { label: "Request Support", icon: ClipboardPlus, href: "/app/maintenance/service-requests?create=1" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/maintenance/operations-log?create=1" }]}/>
    <DepartmentReminders department="Maintenance" base="/app/maintenance"/>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader title="Priority work" description="Urgent and high-priority work orders first"/><div className="divide-y divide-slate-100">{workOrders.map((order) => <button key={order.id} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-slate-50 sm:px-6"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${order.priority === "Urgent" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}><Wrench className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{order.id} · {order.title}</p><p className="mt-1 text-sm text-slate-500">{order.location} · {order.assignee}</p></div><Badge tone={order.priority === "Urgent" ? "urgent" : order.priority === "High" ? "warning" : "neutral"}>{order.status}</Badge><span className="hidden text-xs text-slate-400 sm:block">{order.age}</span></button>)}</div></Card><Card className="h-fit"><CardHeader title="Workload"/><ListRows rows={[{ title: "Preventive maintenance due", detail: "5 inspections due this week", badge: "5", tone: "warning" }, { title: "Recurring room issues", detail: "3 rooms with repeat reports", badge: "Review", tone: "urgent" }, { title: "Waiting for parts", detail: "2 work orders paused", badge: "2", tone: "neutral" }]}/></Card></div><OperationsPreview base="/app/maintenance" role="maintenance"/></div>;
}

export function ManagerDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Maya" description="Operations overview for Ottawa Downtown."/><QuickActions items={[{ label: "Create Announcement", icon: BookPlus, primary: true }, { label: "Assign Task", icon: ClipboardPlus }, { label: "View Reports", icon: FilePlus2 }, { label: "Manage Users", icon: UserPlus }]}/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Summary label="Open issues" value="24" note="Across 4 departments"/><Summary label="Overdue" value="5" note="2 urgent" urgent/><Summary label="Awaiting review" value="3" note="Incidents & payments"/><Summary label="Completed today" value="31" note="Up 12% from Monday" success/></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><OperationsPreview base="/app/manager" role="manager"/><Card><CardHeader title="Department quality" description="Latest inspection scores"/><ListRows rows={[{ title: "Maintenance", detail: "Reviewed July 12", badge: "96%", tone: "success" }, { title: "Front Desk", detail: "Reviewed July 15", badge: "94%", tone: "success" }, { title: "Housekeeping", detail: "Reviewed July 10", badge: "91%", tone: "success" }, { title: "Food & Beverage", detail: "Reviewed June 28", badge: "88%", tone: "warning" }]}/></Card></div>
    <Card><CardHeader title="Recent escalations" description="Items that need management visibility"/><ListRows rows={[{ title: "Room 604 · Repeated AC issue", detail: "Third report in 30 days · Maintenance", badge: "Investigate", tone: "urgent" }, { title: "Virtual card discrepancy", detail: "OTA booking · Room 521 · $184.50", badge: "Assigned", tone: "warning" }, { title: "Guest relocation follow-up", detail: "Incident INC-209 · Front Desk", badge: "Review", tone: "info" }]}/></Card></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><p className="text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>; }
function DashboardEmpty({ message }: { message: string }) { return <div className="px-5 py-8 text-center text-sm text-slate-500 sm:px-6">{message}</div>; }
function Summary({ label, value, note, urgent, success }: { label: string; value: string; note: string; urgent?: boolean; success?: boolean }) { return <Card className="p-4 sm:p-5"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${urgent ? "bg-rose-500" : success ? "bg-emerald-500" : "bg-brand"}`} aria-hidden="true"/><p className="text-xs font-semibold text-slate-500">{label}</p></div><p className="mt-3 text-3xl font-bold tracking-[-.04em] text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></Card>; }
function CompactQualityScore({ department, score }: { department: string; score: number }) { return <div className="flex items-center gap-3 self-start rounded-2xl border border-slate-200 bg-white px-3 py-2 shadow-soft" aria-label={`${department} quality score ${score} percent`}><div className="relative grid size-14 place-items-center rounded-full" style={{ background: `conic-gradient(#10b981 ${score * 3.6}deg, #e2e8f0 0deg)` }}><span className="grid size-[46px] place-items-center rounded-full bg-white text-sm font-bold text-slate-950">{score}%</span></div><div className="hidden pr-1 sm:block"><p className="text-xs font-semibold text-slate-800">Quality score</p><p className="mt-0.5 text-[11px] text-emerald-700">Up 2% · Jul 15</p></div></div>; }
function DepartmentReminders({ department, base }: { department: "Housekeeping" | "Maintenance"; base: string }) {
  const notifications = useDepartmentNotifications(department);
  if (!notifications.length) return null;
  return <Card className="border-sky-200 bg-sky-50/70"><CardHeader title="Front Desk reminders" description={`Follow-up notifications sent to ${department}`}/><div className="divide-y divide-sky-100">{notifications.slice(0, 3).map((notification) => <Link key={notification.id} href={`${base}/service-requests?request=${notification.serviceRequestId}`} className="flex min-h-[72px] items-center gap-3 px-5 py-3 hover:bg-sky-50 sm:px-6"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-sky-700 shadow-sm"><BellRing className="size-4"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-900">{notification.title}</span><span className="mt-1 block text-sm text-slate-600">{notification.message}</span></span><Badge tone="info">Reminder</Badge></Link>)}</div></Card>;
}
function RoomChangeSummary({ workspace }: { workspace: "front-desk" | "housekeeping" }) {
  const updates = useRoomUpdates();
  const lateCheckouts = updates.filter((update) => update.type === "Late checkout");
  const stayovers = updates.filter((update) => update.type.toLowerCase().includes("stayover"));
  const lateByTime = lateCheckouts.reduce<Record<string, number>>((groups, update) => {
    const newTime = update.detail.match(/to (.+?)(?:\.|$)/)?.[1] ?? "Time pending";
    groups[newTime] = (groups[newTime] ?? 0) + 1;
    return groups;
  }, {});
  if (lateCheckouts.length === 0 && stayovers.length === 0) return null;
  return <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-3.5 sm:px-6"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-brand-soft text-brand"><Clock3 className="size-4"/></span><div><h2 className="text-sm font-semibold text-slate-900">Today’s room changes</h2><p className="text-xs text-slate-400">Live operational summary</p></div></div><Link href={`/app/${workspace}/room-updates`} className="text-xs font-semibold text-brand hover:text-brand-strong">View details</Link></div><div className="grid divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0">{lateCheckouts.length > 0 && <section className="flex items-center gap-4 px-5 py-4 sm:px-6" aria-label={`${lateCheckouts.length} late ${lateCheckouts.length === 1 ? "checkout" : "checkouts"}`}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-amber-50 text-xl font-bold text-amber-800">{lateCheckouts.length}</div><div><h3 className="text-sm font-semibold text-slate-900">Late checkouts</h3><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1">{Object.entries(lateByTime).map(([time, count]) => <span key={time} className="text-xs text-slate-500"><strong className="font-semibold text-slate-700">{count}</strong> at {time}</span>)}</div></div></section>}{stayovers.length > 0 && <section className="flex items-center gap-4 px-5 py-4 sm:px-6" aria-label={`${stayovers.length} ${stayovers.length === 1 ? "stayover room" : "stayover rooms"}`}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-emerald-50 text-xl font-bold text-emerald-700">{stayovers.length}</div><div><h3 className="text-sm font-semibold text-slate-900">Stayovers</h3><p className="mt-1 text-xs text-slate-500">{stayovers.length === 1 ? "1 room changed to stayover" : `${stayovers.length} rooms changed to stayover`}</p></div></section>}</div></Card>;
}
