"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, BellRing, BookPlus, CheckCircle2, ClipboardPlus, Clock3, FilePlus2, PackagePlus, Plus, ShieldPlus, Sparkles, UserPlus, Wrench } from "lucide-react";
import { propertyDailyOperations, workOrders } from "@/lib/demo-data";
import { isInformationalRoomChange, useRoomUpdates } from "@/lib/room-update-store";
import { addServiceRequest, useServiceRequests } from "@/lib/service-request-store";
import { sendDepartmentReminder, useDepartmentNotifications } from "@/lib/notification-store";
import { demoEmployees, getDemoEmployeeSession, type DemoEmployee } from "@/lib/demo-auth";
import { useHousekeepingRooms } from "@/lib/housekeeping-room-store";
import { HousekeepingRoomIssueDialog, type HousekeepingRoomIssueDraft } from "../record-dialogs";
import { Badge } from "../ui/badge";
import { Card, CardHeader } from "../ui/card";
import { ListRows, OperationsPreview, PageHeading, QuickActions } from "./shared";

export function FrontDeskDashboard() {
  const requests = useServiceRequests();
  const openStatuses = new Set(["Open", "Assigned", "In Progress", "Waiting"]);
  const needsAttention = requests.filter((request) => request.assigned === "Front Desk" && openStatuses.has(request.status));
  const myOpenItems = requests.filter((request) => (request.createdBy === "Alex Morgan" || request.from === "Front Desk") && openStatuses.has(request.status));
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Alex" description="Front Desk · Ottawa Downtown. Here’s what needs your attention today." actions={<CompactQualityScore department="Front Desk" score={94}/>}/><QuickActions items={[{ label: "Create Service Request", icon: ClipboardPlus, primary: true, href: "/app/front-desk/service-requests?create=1" }, { label: "Add Late Checkout", icon: Clock3, href: "/app/front-desk/room-updates?create=1" }, { label: "Report Incident", icon: ShieldPlus, href: "/app/front-desk/incidents?create=1" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/front-desk/operations-log?create=1" }, { label: "Add Lost & Found Item", icon: PackagePlus, href: "/app/front-desk/lost-found?create=1" }]}/>
    <RoomChangeSummary workspace="front-desk"/>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader title="Needs attention" description="Live work currently assigned to Front Desk"/>{needsAttention.length ? <ListRows rows={needsAttention.map((request) => ({ title: `${request.id} · ${request.title}`, detail: `${request.location} · Requested by ${request.from}`, badge: request.status, tone: request.priority === "Urgent" ? "urgent" : request.status === "In Progress" ? "info" : "warning", href: `/app/front-desk/service-requests?request=${request.id}` }))}/> : <DashboardEmpty message="No Front Desk actions need attention."/>}</Card><Card><CardHeader title="My open items" description="Live status of requests you created"/>{myOpenItems.length ? <ListRows rows={myOpenItems.map((request) => ({ title: `${request.id} · ${request.title}`, detail: `${request.location} · Assigned to ${request.assigned}`, badge: request.status, tone: request.status === "In Progress" ? "info" : request.status === "Waiting" ? "warning" : "neutral", href: `/app/front-desk/service-requests?request=${request.id}` }))}/> : <DashboardEmpty message="You have no open items."/>}</Card></div>
    <OperationsPreview base="/app/front-desk" role="front-desk"/></div>;
}

export function HousekeepingDashboard() {
  const updates = useRoomUpdates();
  const requests = useServiceRequests();
  const assignments = useHousekeepingRooms();
  const [employee, setEmployee] = useState<DemoEmployee | null>(null);
  const [alertMessage, setAlertMessage] = useState("");
  useEffect(() => setEmployee(getDemoEmployeeSession("housekeeping") ?? demoEmployees["sofia.martin"]), []);
  const personalAssignments = assignments.filter((assignment) => assignment.assignedTo === employee?.name);
  const supervisorIssues = requests.filter((request) => request.assigned === "Housekeeping" && request.from === "Housekeeping" && request.status !== "Completed" && request.status !== "Cancelled");
  function reportRoomIssue(draft: HousekeepingRoomIssueDraft) {
    const id = `HK-${Date.now()}`;
    addServiceRequest({ id, title: draft.issue, description: draft.description, location: `Room ${draft.room}`, from: "Housekeeping", assigned: "Housekeeping", assignedUser: "Unassigned", priority: draft.urgency, status: "Open", due: "Today", createdAt: Date.now(), createdBy: employee?.name ?? "Housekeeping employee" });
    sendDepartmentReminder({ department: "Housekeeping", title: `Room ${draft.room}: ${draft.issue}`, message: draft.description, serviceRequestId: id, createdBy: employee?.name ?? "Housekeeping employee", audience: "SUPERVISORS", tone: draft.urgency === "Urgent" ? "urgent" : "warning" });
    setAlertMessage("Room issue sent to your supervisor.");
  }
  function sendSos() {
    const id = `SOS-${Date.now()}`;
    addServiceRequest({ id, title: "Emergency assistance requested", location: "Current assigned area", from: "Housekeeping", assigned: "Housekeeping", assignedUser: "Unassigned", priority: "Urgent", status: "Open", due: "Immediate", createdAt: Date.now(), createdBy: employee?.name ?? "Housekeeping employee" });
    sendDepartmentReminder({ department: "Housekeeping", title: "Emergency SOS", message: `${employee?.name ?? "A Housekeeping employee"} needs immediate supervisor assistance.`, serviceRequestId: id, createdBy: employee?.name ?? "Housekeeping employee", audience: "SUPERVISORS", tone: "urgent" });
    setAlertMessage("Emergency SOS sent to the Housekeeping supervisor.");
  }
  if (employee && !employee.isSupervisor) return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title={`Good morning, ${employee.name}`} description={`Your Housekeeping overview for ${propertyDailyOperations.property}.`} actions={<CompactQualityScore department="Housekeeping" score={91}/>}/>
    <HousekeepingAttendantActions onReport={reportRoomIssue} onSos={sendSos}/>{alertMessage && <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900">{alertMessage}</p>}
    <AttendantRoomSummary assignments={personalAssignments}/><AssignedRoomChanges roomNumbers={personalAssignments.map((assignment) => assignment.room)}/><OperationsPreview base="/app/housekeeping" role="housekeeping"/></div>;
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Housekeeping" description={`Good morning, ${employee?.name ?? "Housekeeping team"}. Department assignments and supervisor follow-up for Ottawa Downtown.`} actions={<CompactQualityScore department="Housekeeping" score={91}/>}/><QuickActions items={[{ label: "Assign Rooms", icon: ClipboardPlus, primary: true, href: "/app/housekeeping/assigned-rooms" }, { label: "Reported Room Issues", icon: AlertTriangle, href: "/app/housekeeping/service-requests" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/housekeeping/operations-log?create=1" }]}/>
    <DepartmentReminders department="Housekeeping" base="/app/housekeeping"/><RoomChangeSummary workspace="housekeeping"/>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Reported room issues" description="Issues sent by Housekeeping employees for assignment"/>{supervisorIssues.length ? <ListRows rows={supervisorIssues.map((request) => ({ title: `${request.location} · ${request.title}`, detail: `${request.createdBy ?? "Housekeeping employee"} · ${request.description ?? "Review required"}`, badge: request.assignedUser === "Unassigned" ? "Needs assignment" : request.status, tone: request.priority === "Urgent" ? "urgent" : "warning", href: `/app/housekeeping/service-requests?request=${request.id}` }))}/> : <DashboardEmpty message="No employee-reported room issues need review."/>}</Card><Card className="h-fit"><CardHeader title="Today’s room board" action={<Link href="/app/housekeeping/assigned-rooms" className="text-xs font-semibold text-brand">Manage assignments</Link>}/><div className="grid grid-cols-2 gap-px overflow-hidden rounded-b-2xl bg-slate-100"><Metric label="Assigned" value={String(assignments.filter((room) => room.assignedTo !== "Unassigned").length)}/><Metric label="Priority" value={String(assignments.filter((room) => room.priority === "Priority").length)}/><Metric label="Ready" value={String(assignments.filter((room) => room.status === "Ready to inspect").length)}/><Metric label="Waiting" value={String(assignments.filter((room) => room.status === "Waiting").length)}/></div></Card></div><OperationsPreview base="/app/housekeeping" role="housekeeping"/></div>;
}

function HousekeepingAttendantActions({ onReport, onSos }: { onReport: (draft: HousekeepingRoomIssueDraft) => void; onSos: () => void }) {
  return <section aria-labelledby="attendant-actions"><h2 id="attendant-actions" className="sr-only">Quick actions</h2><div className="grid gap-3 sm:grid-cols-3"><div className="[&>button]:min-h-[76px] [&>button]:w-full [&>button]:justify-start [&>button]:rounded-2xl [&>button]:px-4"><HousekeepingRoomIssueDialog onCreate={onReport}/></div><Link href="/app/housekeeping/operations-log?create=1" className="group flex min-h-[76px] items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-800 shadow-soft"><span className="grid size-10 place-items-center rounded-xl bg-brand-soft text-brand"><BookPlus className="size-[19px]"/></span>Add Operations Log<ArrowRight className="ml-auto size-4 text-slate-300"/></Link><button type="button" onClick={onSos} className="flex min-h-[76px] items-center gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-left text-sm font-semibold text-amber-950 shadow-soft"><span className="grid size-10 place-items-center rounded-xl bg-amber-200 text-amber-900"><BellRing className="size-[19px]"/></span><span>Emergency SOS<span className="mt-0.5 block text-xs font-normal text-amber-800">Alerts the supervisor now</span></span></button></div></section>;
}

function AttendantRoomSummary({ assignments }: { assignments: ReturnType<typeof useHousekeepingRooms> }) {
  const inProgress = assignments.filter((room) => room.status === "In Progress").length;
  const ready = assignments.filter((room) => room.status === "Ready to inspect").length;
  return <Card className="overflow-hidden"><CardHeader title="Today at a glance" description="Live totals for your shift" action={<Link href="/app/housekeeping/assigned-rooms" className="text-xs font-semibold text-brand">Open room board</Link>}/><div className="grid grid-cols-2 gap-px bg-slate-100 lg:grid-cols-4"><div aria-label={`${assignments.length} ${assignments.length === 1 ? "room" : "rooms"} assigned to you`}><Metric label="My assigned rooms" value={String(assignments.length)}/></div><div aria-label={`${propertyDailyOperations.expectedDepartures} departures expected hotel-wide`}><Metric label="Hotel departures" value={String(propertyDailyOperations.expectedDepartures)}/></div><div aria-label={`${inProgress} assigned rooms in progress`}><Metric label="In progress" value={String(inProgress)}/></div><div aria-label={`${ready} assigned rooms ready to inspect`}><Metric label="Ready to inspect" value={String(ready)}/></div></div></Card>;
}

function AssignedRoomChanges({ roomNumbers }: { roomNumbers: string[] }) {
  const updates = useRoomUpdates().filter((update) => roomNumbers.includes(update.room) && isInformationalRoomChange(update));
  if (!updates.length) return null;
  return <Card><CardHeader title="Changes affecting my rooms" description="Information only · removed automatically at 6:00 PM"/><div className="divide-y divide-slate-100">{updates.map((update, index) => <div key={update.id ?? `${update.room}-${update.type}-${index}`} className="flex min-h-[68px] items-center gap-3 px-5 py-3 sm:px-6"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-soft text-sm font-bold text-brand-strong">{update.room}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">Room {update.room} · {update.type}</p><p className="mt-1 text-xs text-slate-500">No action required</p></div><Badge tone="info">Information</Badge></div>)}</div></Card>;
}

export function MaintenanceDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Maintenance" description="Good morning, Jordan. Prioritized work for Ottawa Downtown." actions={<CompactQualityScore department="Maintenance" score={96}/>}/><QuickActions items={[{ label: "Create Work Order", icon: Wrench, primary: true, href: "/app/maintenance/work-orders?create=1" }, { label: "Report Completion", icon: CheckCircle2, href: "/app/maintenance/work-orders" }, { label: "Request Support", icon: ClipboardPlus, href: "/app/maintenance/service-requests?create=1" }, { label: "Add Operations Log", icon: BookPlus, href: "/app/maintenance/operations-log?create=1" }]}/>
    <DepartmentReminders department="Maintenance" base="/app/maintenance"/>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader title="Priority work" description="Urgent and high-priority work orders first"/><div className="divide-y divide-slate-100">{workOrders.map((order) => <button key={order.id} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-slate-50 sm:px-6"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${order.priority === "Urgent" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}><Wrench className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{order.id} · {order.title}</p><p className="mt-1 text-sm text-slate-500">{order.location} · {order.assignee}</p></div><Badge tone={order.priority === "Urgent" ? "urgent" : order.priority === "High" ? "warning" : "neutral"}>{order.status}</Badge><span className="hidden text-xs text-slate-400 sm:block">{order.age}</span></button>)}</div></Card><Card className="h-fit"><CardHeader title="Workload"/><ListRows rows={[{ title: "Preventive maintenance due", detail: "5 inspections due this week", badge: "5", tone: "warning" }, { title: "Recurring room issues", detail: "3 rooms with repeat reports", badge: "Review", tone: "urgent" }, { title: "Waiting for parts", detail: "2 work orders paused", badge: "2", tone: "neutral" }]}/></Card></div><OperationsPreview base="/app/maintenance" role="maintenance"/></div>;
}

export function ManagerDashboard() {
  return <div className="space-y-6"><PageHeading eyebrow="Monday, August 17" title="Good morning, Maya" description="Operations overview for Ottawa Downtown."/><QuickActions items={[{ label: "Create Announcement", icon: BookPlus, primary: true }, { label: "Assign Task", icon: ClipboardPlus }, { label: "View Reports", icon: FilePlus2 }, { label: "Manage Users", icon: UserPlus }]}/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Summary label="Open issues" value="24" note="Across 4 departments"/><Summary label="Overdue" value="5" note="2 urgent" urgent/><Summary label="Awaiting review" value="3" note="Incidents & payments"/><Summary label="Completed today" value="31" note="Up 12% from Monday" success/></div>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><OperationsPreview base="/app/manager" role="manager"/><Card><CardHeader title="Department quality" description="Latest inspection scores"/><ListRows rows={[{ title: "Maintenance", detail: "Reviewed July 12", badge: "96%", tone: "success" }, { title: "Front Desk", detail: "Reviewed July 15", badge: "94%", tone: "success" }, { title: "Housekeeping", detail: "Reviewed July 10", badge: "91%", tone: "success" }, { title: "Food & Beverage", detail: "Reviewed June 28", badge: "88%", tone: "warning" }]}/></Card></div>
    <Card><CardHeader title="Recent escalations" description="Items that need management visibility"/><ListRows rows={[{ title: "Room 604 · Repeated AC issue", detail: "Third report in 30 days · Maintenance", badge: "Investigate", tone: "urgent" }, { title: "Virtual card discrepancy", detail: "OTA booking · Room 521 · $184.50", badge: "Assigned", tone: "warning" }, { title: "Guest relocation follow-up", detail: "Incident INC-209 · Front Desk", badge: "Review", tone: "info" }]}/></Card></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="bg-white p-5"><p className="text-2xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-slate-500">{label}</p></div>; }
function DashboardEmpty({ message }: { message: string }) { return <div className="px-5 py-8 text-center text-sm text-slate-500 sm:px-6">{message}</div>; }
function Summary({ label, value, note, urgent, success }: { label: string; value: string; note: string; urgent?: boolean; success?: boolean }) { return <Card className="p-4 sm:p-5"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${urgent ? "bg-rose-500" : success ? "bg-emerald-500" : "bg-brand"}`} aria-hidden="true"/><p className="text-xs font-semibold text-slate-500">{label}</p></div><p className="mt-3 text-3xl font-bold tracking-[-.04em] text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></Card>; }
function CompactQualityScore({ department, score }: { department: string; score: number }) { return <div className="flex items-center gap-3 self-start rounded-2xl border border-slate-200 bg-white px-3 py-2 shadow-soft" aria-label={`${department} quality score ${score} percent`}><div className="relative grid size-14 place-items-center rounded-full" style={{ background: `conic-gradient(#10b981 ${score * 3.6}deg, #e2e8f0 0deg)` }}><span className="grid size-[46px] place-items-center rounded-full bg-white text-sm font-bold text-slate-950">{score}%</span></div><div className="hidden pr-1 sm:block"><p className="text-xs font-semibold text-slate-800">Quality score</p><p className="mt-0.5 text-[11px] text-emerald-700">Up 2% · Jul 15</p></div></div>; }
function DepartmentReminders({ department, base }: { department: "Housekeeping" | "Maintenance"; base: string }) {
  const notifications = useDepartmentNotifications(department);
  if (!notifications.length) return null;
  const urgent = notifications.some((notification) => notification.tone === "urgent");
  return <Card className={urgent ? "border-amber-300 bg-amber-50/80" : "border-sky-200 bg-sky-50/70"}><CardHeader title={urgent ? "Supervisor alerts" : "Department notifications"} description={`New follow-up notifications for ${department}`}/><div className={urgent ? "divide-y divide-amber-200" : "divide-y divide-sky-100"}>{notifications.slice(0, 3).map((notification) => <Link key={notification.id} href={`${base}/service-requests?request=${notification.serviceRequestId}`} className={`flex min-h-[72px] items-center gap-3 px-5 py-3 sm:px-6 ${notification.tone === "urgent" ? "hover:bg-amber-100/70" : "hover:bg-sky-50"}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl bg-white shadow-sm ${notification.tone === "urgent" ? "text-amber-800" : "text-sky-700"}`}><BellRing className="size-4"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-900">{notification.title}</span><span className="mt-1 block text-sm text-slate-600">{notification.message}</span></span><Badge tone={notification.tone === "urgent" ? "warning" : "info"}>{notification.tone === "urgent" ? "SOS" : "Notice"}</Badge></Link>)}</div></Card>;
}
function RoomChangeSummary({ workspace, roomNumbers }: { workspace: "front-desk" | "housekeeping"; roomNumbers?: string[] }) {
  const updates = useRoomUpdates();
  const visibleUpdates = roomNumbers ? updates.filter((update) => roomNumbers.includes(update.room)) : updates;
  const lateCheckouts = visibleUpdates.filter((update) => update.type === "Late checkout");
  const earlyCheckouts = visibleUpdates.filter((update) => update.type === "Early checkout");
  const stayovers = visibleUpdates.filter((update) => update.type.toLowerCase().includes("stayover") || update.type.toLowerCase().includes("extension"));
  const lateByTime = lateCheckouts.reduce<Record<string, number>>((groups, update) => {
    const newTime = update.detail.match(/to (.+?)(?:\.|$)/)?.[1] ?? "Time pending";
    groups[newTime] = (groups[newTime] ?? 0) + 1;
    return groups;
  }, {});
  if (lateCheckouts.length === 0 && earlyCheckouts.length === 0 && stayovers.length === 0) return null;
  return <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-3.5 sm:px-6"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-brand-soft text-brand"><Clock3 className="size-4"/></span><div><h2 className="text-sm font-semibold text-slate-900">Today’s room changes</h2><p className="text-xs text-slate-400">Information only · removed at 6:00 PM</p></div></div><Link href={`/app/${workspace}/room-updates`} className="text-xs font-semibold text-brand hover:text-brand-strong">View details</Link></div><div className="grid divide-y divide-slate-100 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{lateCheckouts.length > 0 && <section className="flex items-center gap-4 px-5 py-4 sm:px-6" aria-label={`${lateCheckouts.length} late ${lateCheckouts.length === 1 ? "checkout" : "checkouts"}`}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-amber-50 text-xl font-bold text-amber-800">{lateCheckouts.length}</div><div><h3 className="text-sm font-semibold text-slate-900">Late checkouts</h3><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1">{Object.entries(lateByTime).map(([time, count]) => <span key={time} className="text-xs text-slate-500"><strong className="font-semibold text-slate-700">{count}</strong> at {time}</span>)}</div></div></section>}{earlyCheckouts.length > 0 && <section className="flex items-center gap-4 px-5 py-4 sm:px-6" aria-label={`${earlyCheckouts.length} early ${earlyCheckouts.length === 1 ? "checkout" : "checkouts"}`}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-sky-50 text-xl font-bold text-sky-800">{earlyCheckouts.length}</div><div><h3 className="text-sm font-semibold text-slate-900">Early checkouts</h3><p className="mt-1 text-xs text-slate-500">{earlyCheckouts.length} {earlyCheckouts.length === 1 ? "room" : "rooms"}</p></div></section>}{stayovers.length > 0 && <section className="flex items-center gap-4 px-5 py-4 sm:px-6" aria-label={`${stayovers.length} ${stayovers.length === 1 ? "stayover room" : "stayover rooms"}`}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-emerald-50 text-xl font-bold text-emerald-700">{stayovers.length}</div><div><h3 className="text-sm font-semibold text-slate-900">Stayovers</h3><p className="mt-1 text-xs text-slate-500">{stayovers.length === 1 ? "1 room changed to stayover" : `${stayovers.length} rooms changed to stayover`}</p></div></section>}</div></Card>;
}
